/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Users: () => import('#controllers/admin/users_controller'),
  },
  IntraAuth: () => import('#controllers/intra_auth_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Session: () => import('#controllers/session_controller'),
  Workshop: () => import('#controllers/workshop_controller'),
}
